!!python/object/apply:collections.OrderedDict
- - - learning_rate
    - 0.0001
  - - n_envs
    - 10
  - - n_timesteps
    - 400000
  - - normalize
    - norm_obs: true
      norm_reward: false
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - net_arch:
        pi:
        - 128
        - 128
        vf:
        - 128
        - 128
